BACKPORT: seccomp: add filter_count field for KernelSU
* KernelSU requires struct seccomp to have atomic_t filter_count ,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:

 error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708
Actual Commit: GrapheneOS-Archive/kernel_common-5.10@c818c03

Change-Id: I0ab7e33eebd8413851ba29cd2583ec5f14ddd556
Signed-off-by: Kees Cook <keescook@chromium.org>